export const announcements = [
    {
        "id": "1",
        "owner": "John",
        "title": "Buying MacBook laptops",
        "text": "New software company is looking for buying brand new MacBooks",
        "startDate": "1/1/2020",
        "endDate": "2/3/2020",
        "state": "active",
    },
    {
        "id": "2",
        "owner": "Doe",
        "title": "Buying MacBook laptops",
        "text": "New software company is looking for buying brand new MacBooks",
        "startDate": "1/1/2020",
        "endDate": "2/3/2020",
        "state": "deactivated",
    },
    {
        "id": "3",
        "owner": "Smith",
        "title": "Buying MacBook laptops",
        "text": "New software company is looking for buying brand new MacBooks",
        "startDate": "1/1/2020",
        "endDate": "2/3/2020",
        "state": "deactivated",
    },
    {
        "id": "4",
        "owner": "Kellerman",
        "title": "Buying MacBook laptops",
        "text": "New software company is looking for buying brand new MacBooks",
        "startDate": "1/1/2020",
        "endDate": "2/3/2020",
        "state": "declined",
    },
    {
        "id": "5",
        "owner": "Alnord",
        "title": "Buying MacBook laptops",
        "text": "New software company is looking for buying brand new MacBooks",
        "startDate": "1/1/2020",
        "endDate": "2/3/2020",
        "state": "pending",
    },
    {
        "id": "6",
        "owner": "Rubenburg",
        "title": "Buying MacBook laptops",
        "text": "New software company is looking for buying brand new MacBooks",
        "startDate": "1/1/2020",
        "endDate": "2/3/2020",
        "state": "pending",
    },
    {
        "id": "7",
        "owner": "O'Hora",
        "title": "Buying MacBook laptops",
        "text": "New software company is looking for buying brand new MacBooks",
        "startDate": "1/1/2020",
        "endDate": "2/3/2020",
        "state": "accepted",
    },
    {
        "id": "8",
        "owner": "Robinson",
        "title": "Buying MacBook laptops",
        "text": "New software company is looking for buying brand new MacBooks",
        "startDate": "1/1/2020",
        "endDate": "2/3/2020",
        "state": "active",
    },
    {
        "id": "9",
        "owner": "O'Hora",
        "title": "Buying MacBook laptops",
        "text": "New software company is looking for buying brand new MacBooks",
        "startDate": "1/1/2020",
        "endDate": "2/3/2020",
        "state": "accepted",
    },
    {
        "id": "10",
        "owner": "O'Hora",
        "title": "Buying MacBook laptops",
        "text": "New software company is looking for buying brand new MacBooks",
        "startDate": "1/1/2020",
        "endDate": "2/3/2020",
        "state": "accepted",
    },
    {
        "id": "11",
        "owner": "Robinson",
        "title": "Buying MacBook laptops",
        "text": "New software company is looking for buying brand new MacBooks",
        "startDate": "1/1/2020",
        "endDate": "2/3/2020",
        "state": "deactivated",
    },
];