export const announcements = [
    {
        "id": "1",
        "owner": "Doe",
        "title": "Buying MacBook laptops",
        "text": "New software company is looking for buying brand new MacBooks",
        "startDate": "1/1/2020",
        "endDate": "2/3/2020",
        "status": "active",
    },
    {
        "id": "2",
        "owner": "Shinnong",
        "title": "Buying Dell laptops",
        "text": "New software company is looking for buying brand new MacBooks",
        "startDate": "1/1/2020",
        "endDate": "2/3/2020",
        "status": "deactivated",
    },
    {
        "id": "3",
        "owner": "Doe",
        "title": "Buying HP laptops",
        "text": "New software company is looking for buying brand new MacBooks",
        "startDate": "1/1/2020",
        "endDate": "2/3/2020",
        "status": "deactivated",
    },
    {
        "id": "4",
        "owner": "Smith",
        "title": "Buying MacBook laptops",
        "text": "New software company is looking for buying brand new MacBooks",
        "startDate": "1/1/2020",
        "endDate": "2/3/2020",
        "status": "declined",
    },
    {
        "id": "5",
        "owner": "O'Hora",
        "title": "Buying Acer laptops",
        "text": "New software company is looking for buying brand new MacBooks",
        "startDate": "1/1/2020",
        "endDate": "2/3/2020",
        "status": "pending",
    },
    {
        "id": "6",
        "owner": "Robinson",
        "title": "Buying MacBook laptops",
        "text": "New software company is looking for buying brand new MacBooks",
        "startDate": "1/1/2020",
        "endDate": "2/3/2020",
        "status": "pending",
    },
    {
        "id": "7",
        "owner": "Doe",
        "title": "Buying MacBook laptops",
        "text": "New software company is looking for buying brand new MacBooks",
        "startDate": "1/1/2020",
        "endDate": "2/3/2020",
        "status": "accepted",
    },
    {
        "id": "8",
        "owner": "Scott",
        "title": "Buying MacBook laptops",
        "text": "New software company is looking for buying brand new MacBooks",
        "startDate": "1/1/2020",
        "endDate": "2/3/2020",
        "status": "active",
    },
    {
        "id": "9",
        "owner": "Shinnong",
        "title": "Buying MacBook laptops",
        "text": "New software company is looking for buying brand new MacBooks",
        "startDate": "1/1/2020",
        "endDate": "2/3/2020",
        "status": "accepted",
    },
    {
        "id": "10",
        "owner": "Min Young",
        "title": "Buying MacBook laptops",
        "text": "New software company is looking for buying brand new MacBooks",
        "startDate": "1/1/2020",
        "endDate": "2/3/2020",
        "status": "accepted",
    },
    {
        "id": "11",
        "owner": "Min Young",
        "title": "Buying MacBook laptops",
        "text": "New software company is looking for buying brand new MacBooks",
        "startDate": "1/1/2020",
        "endDate": "2/3/2020",
        "status": "deactivated",
    },
];